version: '2.3'

services:

  statping:
    container_name: statping
    image: stevenliuyi/statping:latest
    restart: always
    ports:
      - 80:8080
    volumes:
      - ./statping:/app
    expose:
      - 8080
    environment:
      NAME: Statping
      DESCRIPTION: You'll need to input your own Database information in Setup process
