version: '2.3'

services:

  nginx:
    container_name: nginx
    image: jwilder/nginx-proxy
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    networks:
      - internet
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./statping/nginx/certs:/etc/nginx/certs:ro
      - ./statping/nginx/vhost:/etc/nginx/vhost.d
      - ./statping/nginx/html:/usr/share/nginx/html:ro
      - ./statping/nginx/dhparam:/etc/nginx/dhparam
    environment:
      DEFAULT_HOST: localhost

  statping:
    container_name: statping
    image: stevenliuyi/statping:latest
    restart: always
    networks:
      - internet
      - database
    depends_on:
      - postgres_statping
    volumes:
      - ./statping/app:/app
    environment:
      VIRTUAL_HOST: localhost
      VIRTUAL_PORT: 8080
      DB_CONN: postgres
      DB_HOST: postgres_statping
      DB_USER: statping
      DB_PASS: password123
      DB_DATABASE: statping
      NAME: EC2 Example
      DESCRIPTION: This is a Statping Docker Compose instance

  postgres_statping:
    container_name: postgres_statping
    image: postgres
    restart: always
    networks:
      - database
    volumes:
      - ./statping/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: statping
      POSTGRES_DB: statping

networks:
  internet:
    driver: bridge
  database:
    driver: bridge
